[tool.poetry]
name = "your-middleware"
version = "0.1.0"
description = "A Django middleware for audit logging."
authors = ["Your Name <youremail@yourcompany.com>"]

[tool.poetry.dependencies]
python = "^3.12"
Django = "^4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
